PR: Restructuring & Refactoring Entity-classes & Model-classes
Gepardec/gepardec-gamertrack pull request #36
Opened 2024-12-30 09:30 UTC by Jaroslav380

Moved @Entity-classes to the db-module
Created new Model-classes

Placed the peristence.xml in the db-module

Transporting data between the layers using the model-classes instead of Dto's
Commands and RestDto are using model-classes instead of model-class-ids

Refactored Repository, Service & all Mappers
Refactored RepositoryTests, ServiceTests, HttpRequests & all mapperTests

and some small BugFixes

closes #27

2025-01-07 02:10 UTC, Xaeras requested changes
Hello! Ich habe ein paar Kleinigkeiten noch gefunden. Im großen und ganzen siehts gut aus! Ich habe mir leider die .http und integration tests noch nicht angeschaut, aber ich hoffe einfach dass die für euch mal passen :)

2025-01-07 02:10 UTC, Xaeras commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/GameRepositoryImpl.java
> +@Transactional
Ich würde das Transactional nicht pauschal über alle Repositories geben, sondern stattdessen bewusst über die Serviceklassen, wo ihr es eh schon habt :)
Außer ich vergesse gerade auf etwas :+1:

2025-01-07 02:10 UTC, Xaeras commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/MatchRepositoryImpl.java
> +@Transactional
Gleiches hier:
Ich würde das Transactional nicht pauschal über alle Repositories geben, sondern stattdessen bewusst über die Serviceklassen, wo ihr es eh schon habt :)
Außer ich vergesse gerade auf etwas :+1:

2025-01-07 02:10 UTC, Xaeras commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/ScoreRepositoryImpl.java
> +@Transactional
Gleiches hier:
Ich würde das Transactional nicht pauschal über alle Repositories geben, sondern stattdessen bewusst über die Serviceklassen, wo ihr es eh schon habt :)
Außer ich vergesse gerade auf etwas :+1:

2025-01-07 02:10 UTC, Xaeras commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/UserRepositoryImpl.java
> +@Transactional
Gleiches hier:
Ich würde das Transactional nicht pauschal über alle Repositories geben, sondern stattdessen bewusst über die Serviceklassen, wo ihr es eh schon habt :)
Außer ich vergesse gerade auf etwas :+1:

2025-01-07 07:24 UTC, Jaroslav380 commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/UserRepositoryImpl.java
> +@Transactional
Wir hatten anfangs das Transactional nur über den Serviceklassen. Jedoch verlangen die Repository arquillian Integrationstest, dass die Repositories ebenfalls transactional sind.

2025-01-07 07:27 UTC, Jaroslav380 commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/ScoreRepositoryImpl.java
> +@Transactional
Wir hatten anfangs das Transactional nur über den Serviceklassen. Jedoch verlangen die Repository arquillian Integrationstest, dass die Repositories ebenfalls transactional sind.

2025-01-07 07:27 UTC, Jaroslav380 commented on gamertrack-db/src/main/java/com/gepardec/adapter/output/persistence/repository/GameRepositoryImpl.java
> +@Transactional
Wir hatten anfangs das Transactional nur über den Serviceklassen. Jedoch verlangen die Repository arquillian Integrationstest, dass die Repositories ebenfalls transactional sind.

2025-01-07 07:29 UTC, alekszivko commented on gamertrack-domain/src/test/java/com/gepardec/TestFixtures.java
> +      Match match = match((long) i + 1);
Hab mir gedacht, dass es bei datenbanken üblich ist, dass die Ids mit 1 starten habs dann deshalb geändert. Scheint aber auch nicht 100% immer so zu sein da auch 0 bzw. negative ids möglich sind

2025-01-13 13:22 UTC, Xaeras approved these changes
Super gemacht! Ich habe zwei Kleinigkeiten noch in den Commits hier geändert:

- Casing von parameter https://github.com/Gepardec/gepardec-gamertrack/commit/a5ccb37fd13cc826badd23891329539cac122e47
- Unused imports https://github.com/Gepardec/gepardec-gamertrack/commit/ef9e3be5a4ef337cb6295cbe58e6a381a48a73ff

2025-01-16 08:41 UTC, merged